# Preparation for the training
Python, numpy, scipy, pytorch basics, environment

Prepared by OG

## Show how to download notebook from Github

Open it on Google drive

How to run a cell

## Python basics

Variable assignments

In [ ]:
x = 5
x

5

Variable calculations

In [ ]:
x+20
#x-2
#x*5
#x**2
#x%2
#x/float(2)

25

Types and Type conversion

In [ ]:
str(2)
int("2")

2

In [ ]:
float(3)
bool(1)

3.0

Asking for help

In [ ]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

Strings and String Operations


In [ ]:
my_string = "thisisOnosstring"

In [ ]:
my_string + 'isit'

'thisisOnosstringisit'

In [ ]:
'i' in my_string

True

In [ ]:
my_string[3]

's'

In [ ]:
my_string[4:9]

'isOno'

String methods

In [ ]:
my_string.upper()

'THISISONOSSTRING'

In [ ]:
my_string.lower()

'thisisonosstring'

In [ ]:
my_string.count('w')

0

In [ ]:
my_string.replace('e', 'i')

'thisisOnosstring'

In [ ]:
my_string.strip()

'thisisOnosstring'

Lists and Operations

In [ ]:
a = 'is'
b = 'nice'
my_list = ['my', 'list', a, b]
my_list2 = [[4, 5, 6, 7], [3, 4, 5, 6]]

Selecting list elements

In [ ]:
my_list[1]

'list'

In [ ]:
my_list[-3]

'list'

In [ ]:
my_list[1:3]

['list', 'is']

In [ ]:
my_list[1:]

['list', 'is', 'nice']

In [ ]:
my_list[:3]

['my', 'list', 'is']

In [ ]:
my_list[:]

['my', 'list', 'is', 'nice']

In [ ]:
my_list2[1][0]


3

In [ ]:
my_list2[1][:2]

[3, 4]

List Operations

In [ ]:
my_list + my_list

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [ ]:
my_list * 2

['my', 'list', 'is', 'nice', 'my', 'list', 'is', 'nice']

In [ ]:
my_list2

[[4, 5, 6, 7], [3, 4, 5, 6]]

List Methods

In [ ]:
my_list.index(a)

2

In [ ]:
my_list.count(a)

1

In [ ]:
my_list.append('!')
my_list

['my', 'list', 'is', 'nice', '!']

In [ ]:
my_list.remove('!')

In [ ]:
del(my_list[0:1])

In [ ]:
my_list.reverse()

In [ ]:
my_list.extend('!')

In [ ]:
my_list.pop(-1)

'!'

In [ ]:
my_list.insert(0, '!')

In [ ]:
my_list.sort()

Import libraries


In [ ]:
import numpy

In [ ]:
import numpy as np

In [ ]:
from math import pi

## Numpy arrays

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

[Source](https://en.wikipedia.org/wiki/NumPy)

In [ ]:
my_list =[1, 2, 3, 4]

In [ ]:
my_array = np.array(my_list)

In [ ]:
my_2ndarray = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
my_array[1]

2

In [ ]:
my_array[0:2]

array([1, 2])

In [ ]:
my_2ndarray[:,0]

array([1, 4])

In [ ]:
my_array >3

array([False, False, False,  True])

In [ ]:
my_array *2

array([2, 4, 6, 8])

In [ ]:
my_array + np.array([5, 6, 7, 8])

array([ 6,  8, 10, 12])

Numpy array functions

In [ ]:
my_array.shape

(4,)

In [ ]:
other_array = [5, 6, 7, 8]
other_array = np.array(other_array)
other_array

array([5, 6, 7, 8])

In [ ]:
np.append(my_array, other_array)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.insert(my_array, 1, 5)

array([1, 5, 2, 3, 4])

In [ ]:
np.delete(my_array, [1])

array([1, 3, 4])

In [ ]:
np.mean(my_array)

2.5

In [ ]:
np.median(my_array)

2.5

In [ ]:
np.std(my_array)

1.118033988749895

In [ ]:
np.dot(my_array, other_array)

70

Numpy Broadcasting

In [ ]:
import numpy as np
salary = np.array([2000, 4000, 6000])
salary_bump = 1.1

print(salary * salary_bump)

[2200. 4400. 6600.]


Boolean Indexing

In [ ]:
import numpy as np
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

indices = np.array([[False, False, True], 
                    [False, False, False], 
                    [True, True, False]])

print(a[indices])

[3 7 8]


How to search arrays

In [ ]:
import numpy as np
X = np.array([[1, 0, 0], 
              [0, 2, 2], 
              [3, 0, 0]])

print(np.nonzero(X))

(array([0, 1, 1, 2]), array([0, 1, 2, 0]))


In [ ]:
import numpy as np

X = np.array(
    [[42, 40, 41, 43, 44, 43], 
     [30, 31, 29, 29, 29, 30], 
     [8, 13, 31, 11, 11, 9], 
     [11, 11, 12, 13, 11, 12]]
)

cities = np.array(['Hong Kong', 'New York', 'Berlin', 'Montreal'])

polluted = set(cities[np.nonzero(X>np.average(X))[0]])
print(polluted)

{'New York', 'Berlin', 'Hong Kong'}


In [ ]:
cities[[0, 1, 2]]


array(['Hong Kong', 'New York', 'Berlin'], dtype='<U9')

## Pandas

Pandas is a software library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series. 

[Source](https://en.wikipedia.org/wiki/Pandas_(software)


Creating dataframe

In [3]:
import pandas as pd

df = pd.DataFrame(
              {"a" : [4 ,5, 6],
               "b" : [7, 8, 9],
               "c" : [10, 11, 12]},
            index = [1, 2, 3])

In [5]:
df

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [8]:
df2 = pd.DataFrame( [[4, 7, 10], [5, 8, 11],
          [6, 9, 12]],
         index=[1, 2, 3],
         columns=['a', 'b', 'c'])
df2

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [9]:
df3 = pd.DataFrame(
              {"a" : [4 ,5, 6],
               "b" : [7, 8, 9],
               "c" : [10, 11, 12]},
    index = pd.MultiIndex.from_tuples(
              [('d',1),('d',2),('e',2)],
                 names=['n','v']))
df3

a  b   c
n v          
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

Reshaping data

In [10]:
pd.melt(df)
#Gather columns into rows.

variable  value
0        a      4
1        a      5
2        a      6
3        b      7
4        b      8
5        b      9
6        c     10
7        c     11
8        c     12

In [12]:
df.pivot(columns='a', values='b')
#Spread rows into columns.

a    4    5    6
1  7.0  NaN  NaN
2  NaN  8.0  NaN
3  NaN  NaN  9.0

In [13]:
pd.concat([df,df2])
#Append rows of DataFrames

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12
1  4  7  10
2  5  8  11
3  6  9  12

In [14]:
pd.concat([df,df2], axis=1)
#Append columns of DataFrames

a  b   c  a  b   c
1  4  7  10  4  7  10
2  5  8  11  5  8  11
3  6  9  12  6  9  12

In [23]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [28]:
df = pd.read_csv('/content/drive/My Drive/cars.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  32 non-null     object 
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64  
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64  
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64  
 9   am          32 non-null     int64  
 10  gear        32 non-null     int64  
 11  carb        32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [29]:
df.sort_values('mpg')
#Order rows by values of a column (low to high).


Unnamed: 0   mpg  cyl   disp   hp  ...   qsec  vs  am  gear  carb
15  Lincoln Continental  10.4    8  460.0  215  ...  17.82   0   0     3     4
14   Cadillac Fleetwood  10.4    8  472.0  205  ...  17.98   0   0     3     4
23           Camaro Z28  13.3    8  350.0  245  ...  15.41   0   0     3     4
6            Duster 360  14.3    8  360.0  245  ...  15.84   0   0     3     4
16    Chrysler Imperial  14.7    8  440.0  230  ...  17.42   0   0     3     4
30        Maserati Bora  15.0    8  301.0  335  ...  14.60   0   1     5     8
13          Merc 450SLC  15.2    8  275.8  180  ...  18.00   0   0     3     3
22          AMC Javelin  15.2    8  304.0  150  ...  17.30   0   0     3     2
21     Dodge Challenger  15.5    8  318.0  150  ...  16.87   0   0     3     2
28       Ford Pantera L  15.8    8  351.0  264  ...  14.50   0   1     5     4
11           Merc 450SE  16.4    8  275.8  180  ...  17.40   0   0     3     3
12           Merc 450SL  17.3    8  275.8  180  ...  17.60   0   0     3     3
10            Merc 280C  17.8    6  167.6  123  ...  18.90   1   0     4     4
5               Valiant  18.1    6  225.0  105  ...  20.22   1   0     3     1
4     Hornet Sportabout  18.7    8  360.0  175  ...  17.02   0   0     3     2
9              Merc 280  19.2    6  167.6  123  ...  18.30   1   0     4     4
24     Pontiac Firebird  19.2    8  400.0  175  ...  17.05   0   0     3     2
29         Ferrari Dino  19.7    6  145.0  175  ...  15.50   0   1     5     6
0             Mazda RX4  21.0    6  160.0  110  ...  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110  ...  17.02   0   1     4     4
3        Hornet 4 Drive  21.4    6  258.0  110  ...  19.44   1   0     3     1
31           Volvo 142E  21.4    4  121.0  109  ...  18.60   1   1     4     2
20        Toyota Corona  21.5    4  120.1   97  ...  20.01   1   0     3     1
8              Merc 230  22.8    4  140.8   95  ...  22.90   1   0     4     2
2            Datsun 710  22.8    4  108.0   93  ...  18.61   1   1     4     1
7             Merc 240D  24.4    4  146.7   62  ...  20.00   1   0     4     2
26        Porsche 914-2  26.0    4  120.3   91  ...  16.70   0   1     5     2
25            Fiat X1-9  27.3    4   79.0   66  ...  18.90   1   1     4     1
27         Lotus Europa  30.4    4   95.1  113  ...  16.90   1   1     5     2
18          Honda Civic  30.4    4   75.7   52  ...  18.52   1   1     4     2
17             Fiat 128  32.4    4   78.7   66  ...  19.47   1   1     4     1
19       Toyota Corolla  33.9    4   71.1   65  ...  19.90   1   1     4     1

[32 rows x 12 columns]

In [ ]:
df.sort_values('mpg',ascending=False)
#Order rows by values of a column (high to low).
df.rename(columns = {'y':'year'})
#Rename the columns of a DataFrame
df.sort_index()
#Sort the index of a DataFrame
df.reset_index()
#Reset index of DataFrame to row numbers, moving index to columns.
df.drop(columns=['Length','Height'])
#Drop columns from DataFrame

Subset row operations

In [ ]:
df[df.Length > 7]
#Extract rows that meet logical criteria.
df.drop_duplicates()
#Remove duplicate rows (only considers columns).
df.head(n)
#Select first n rows.
df.tail(n)
#Select last n rows.
df.sample(frac=0.5)
#Randomly select fraction of rows.
df.sample(n=10)
#Randomly select n rows.
df.iloc[10:20]
#Select rows by position.
df.nlargest(n, 'value')
#Select and order top n entries.
df.nsmallest(n, 'value')
#Select and order bottom n entries.

In [30]:
df.columns

Index(['Unnamed: 0', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs',
       'am', 'gear', 'carb'],
      dtype='object')

Subset column variables

In [ ]:
df[['mpg','cyl','disp']]
#Select multiple columns with specific names.
df['mpg'] or df.mpg
#Select single column with specific name.
df.filter(regex='+t')
#Select columns whose name matches regular expression regex.

Summarize data

In [ ]:
df['cyl'].value_counts()
# Count number of rows with each unique value of variable
len(df)
# of rows in DataFrame.
df['cyl'].nunique()
# of distinct values in a column.
df.describe()
# Basic descriptive statistics for each column (or GroupBy)
sum()
#Sum values of each object.
count()
#Count non-NA/null values of each object.
median()
#Median value of each object.
quantile([0.25,0.75])
#Quantiles of each object.
apply(function)
#Apply function to each object.
min()
#Minimum value in each object.
max()
#Maximum value in each object.
mean()
#Mean value of each object.
var()
#Variance of each object.
std()
#Standard deviation of each object.

Handling missing data

In [ ]:
df.dropna()
#Drop rows with any column having NA/null data.
df.fillna(value)
#Replace all NA/null data with value.

Make new columns

In [ ]:
df.assign(Area=lambda df: df.Length*df.Height)
#Compute and append one or more new columns.
df['Volume'] = df.Length*df.Height*df.Depth #Add single column.
pd.qcut(df.col, n, labels=False) #Bin column into n buckets.
max(axis=1) #Element-wisemax. 
min(axis=1) #Element-wisemin.
clip(lower=-10,upper=10)  #Trim values at input thresholds 
abs() # Absolute value.



Group data

In [ ]:
df.groupby(by="col") #Return a GroupBy object, grouped by values in column named "col".
df.groupby(level="ind") #Return a GroupBy object, grouped by values in index level named "ind".

In [ ]:
size() #Size of each group.

In [ ]:
agg(function) #Aggregate group using function.

In [ ]:
shift(1) #Copy with values shifted by 1.
rank(method='dense') #Ranks with no gaps.
rank(method='min') #Ranks. Ties get min rank.
rank(pct=True) #Ranks rescaled to interval [0, 1].
rank(method='first') #Ranks. Ties go to first value.
shift(-1) #Copywithvalueslaggedby1.
cumsum() #Cumulative sum.
cummax() #Cumulative max.
cummin() #Cumulative min.
cumprod() #Cumulative product.

In [ ]:
pd.merge(adf, bdf, how='left', on='x1') #Join matching rows from bdf to adf.

## Scikit-Learn

Loading the data

In [ ]:
import numpy as np
X = np.random.random((10, 5))
y = np.array(['M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'F'])
X[X<0.7] =0

Training and Test data

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state =0)

Preprocessing the data

Standardization

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X_train)
standardized_X = scaler.transform(X_train)
standardized_X_test = scaler.transform(X_test)

Normalization

In [ ]:
from sklearn.preprocessing import Normalizer
scaler = Normalizer().fit(X_train)
normalized_X = scaler.transform(X_train)
normalized_X_test = scaler.transform(X_test)

Binarization

In [ ]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=0.0).fit(X)
binary_X = binarizer.transform(X)

Encoding Categorical Features

In [ ]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder()
y = enc.fit_transform(y)

Imputing missing values

In [ ]:
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values = 0, strategy = 'mean', axis=0)
imp.fit_transform(X_train)

Generating Polynomial Features

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(5)
poly.fit_transform(X)

# PyTorch Basics


In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [ ]:
#from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
#from another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8314, 0.3387],
        [0.1434, 0.1750]]) 



In [ ]:
#with random or constant value
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8885, 0.3996, 0.3628],
        [0.6700, 0.1642, 0.3731]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [ ]:
#Standard numpy-like indexing and slicing:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

In [ ]:
#Joining tensor
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)


tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
#Arithmetic operations
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [ ]:
#Single-element tensors
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [ ]:
#In-place operations
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [ ]:
#Tensor to NumPy array
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [ ]:
#A change in the tensor reflects in the NumPy array.
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [ ]:
#NumPy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
#Changes in the NumPy array reflects in the tensor.
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


## Loading a Dataset

In [ ]:
import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt


training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw




Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw




Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw




Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


## Iterating and Visualizing the Dataset

In [ ]:
labels_map = {
    0: "T-Shirt",
    1: "Trouser",
    2: "Pullover",
    3: "Dress",
    4: "Coat",
    5: "Sandal",
    6: "Shirt",
    7: "Sneaker",
    8: "Bag",
    9: "Ankle Boot",
}
figure = plt.figure(figsize=(8, 8))
cols, rows = 3, 3
for i in range(1, cols * rows + 1):
    sample_idx = torch.randint(len(training_data), size=(1,)).item()
    img, label = training_data[sample_idx]
    figure.add_subplot(rows, cols, i)
    plt.title(labels_map[label])
    plt.axis("off")
    plt.imshow(img.squeeze(), cmap="gray")
plt.show()

# References

[Numpy documentation] (https://numpy.org/devdocs/reference/)
[Pandas documentation](https://pandas.pydata.org/docs/reference/index.html)
[Scikit documentation](https://scikit-learn.org/stable/modules/classes.html#)
[PyTorch documentation](https://pytorch.org/docs/stable/index.html)